version: '3.8'

services:
  # 1. Base de Datos PostgreSQL
  db: 
    image: postgres:15-alpine
    container_name: altairis_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AltairisAlexMVP2026!
      - POSTGRES_DB=AltairisDb
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. Administrador de Base de Datos 
  pgadmin:
    image: dpage/pgadmin4
    container_name: altairis_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@altairis.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80" 
    depends_on:
      - db
    restart: always

  # 3. Backend (Web API .NET 8)
  backend:
    build: 
      context: . # Corregido: El contexto es la carpeta actual donde está el .sln
      dockerfile: Altaris.API/Dockerfile 
    container_name: altairis_api
    ports:
      - "5150:8080" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=AltairisDb;Username=postgres;Password=AltairisAlexMVP2026!
      - Jwt__Key=Aestro19SecretUniverseForAltaris
      - Jwt__Issuer=AltairisAPI
      - Jwt__Audience=AltairisFront
    depends_on:
      - db
    restart: always

  # 4. Frontend (Next.js)
  frontend:
    build: 
      context: ./altairis-frontend # Corregido: Ruta directa a la carpeta del front
    container_name: altairis_web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5150/api
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: